trigger:
- main

pool:
  vmImage: 'windows-latest'

steps: 

- task: DotNetCoreCLI@2
  displayName: "compilacion"
  inputs:
    azureSubscription: 'Azure subscription 1(db2f2e2a-0772-46b5-8a3d-9777e10e0a81)'
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '/demo-taller'

- task: DotNetCoreCLI@2
  displayName: "publicacion"
  inputs:
    azureSubscription: 'Azure subscription 1(db2f2e2a-0772-46b5-8a3d-9777e10e0a81)'
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo-taller'

- task: DotNetCoreCLI@2
  displayName: "pruebas"
  inputs:
    azureSubscription: 'Azure subscription 1(db2f2e2a-0772-46b5-8a3d-9777e10e0a81)'
    command: 'test'
    projects: '**/*Tests.csproj'
    publishTestResults: true

- task: AzureRmWebAppDeployment@5
  displayName: "despliegue"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(db2f2e2a-0772-46b5-8a3d-9777e10e0a81)'
    appType: 'webApp'
    WebAppName: 'AplicadaTallerJDMK'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

