trigger:
- main

pool:
  name: MyAgentPool

steps:
# 1 Instalar SDK .NET 8
- task: UseDotNet@2
  displayName: "Instalar .NET SDK 8.0"
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: false

# 2 Compilar
- task: DotNetCoreCLI@2
  displayName: "Compilación"
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo-taller'

# 3 Publicar
- task: DotNetCoreCLI@2
  displayName: "Publicación"
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: '$(System.DefaultWorkingDirectory)/demo-taller'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

# 4 Ejecutar pruebas
- task: DotNetCoreCLI@2
  displayName: "Pruebas"
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    publishTestResults: true

# 5 Desplegar en Azure Web App
- task: AzureRmWebAppDeployment@5
  displayName: "Despliegue en Azure Web App"
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(db2f2e2a-0772-46b5-8a3d-9777e10e0a81)'
    appType: 'webApp'
    WebAppName: 'AplicadaTallerJDMK'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
